# Generated by Django 3.1.2 on 2020-11-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201106_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='thumbnail.jpeg', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_title',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
