# Generated by Django 3.1.2 on 2020-11-17 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20201117_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='update_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
