# Generated by Django 3.1.2 on 2020-11-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_avatar.png', upload_to='profiles'),
        ),
    ]
