# Generated by Django 3.1.2 on 2020-11-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201106_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_avatar.png', upload_to='profile_pic'),
        ),
    ]
